apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-pipelineruns
spec:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-runner
            image: bitnami/kubectl
            command: 
              - 'kubectl'
              - 'delete'
              - 'pod'
              - '--field-selector=status.phase=Succeeded'
          restartPolicy: Never