---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-opa-gatekeeper
  labels:
    app.kubernetes.io/instance: tekton-pipeline
    app.kubernetes.io/component: controller
spec:
  steps:
    - name: opa-gatekeeper-test-function
      image: bitnami/kubectl
      script: |
        echo "----Start Get POD status Test Function---"
        kubectl get po
        echo "----End Get---"